feat: outputs in definition consumed by ecs_service
nexient-llc/tf-aws-module-ecs_task pull request #2
Opened 2022-09-29 21:58 UTC by wright-nexient

This is a draft of a PR.

One comment needs to be removed if this is pushed into main. 

Will change, but it is my explanation/reasoning behind renaming an `output`

Feedback welcome, then will draft a new PR for merge into main.

2022-09-29 22:01 UTC, cjharries-nexient requested changes
The tests currently fail. You'll need to update the tests to handle the new variable name.

2022-09-29 22:01 UTC, wright-nexient commented
> The tests currently fail. You'll need to update the tests to handle the new variable name.

good catch, thanks

2022-09-29 22:07 UTC, wright-nexient commented
@cjharries-nexient 

Updated, passing tests.
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/105006874/193150655-1a289580-0b45-4eed-a2e2-49c7cd649d46.png">

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/105006874/193150637-c158dbc8-f19a-4535-8883-2a9bf0d29cae.png">

2022-09-30 17:21 UTC, cjharries-nexient approved these changes

2022-09-30 17:22 UTC, merged